### ISSUE TITLE
20303 : authorization token is invalid or contains invalid field(s) null

### ISSUE THREAD

**Issue by amigax** [VirgilSecurity/virgil-e3kit-kotlin#18]
Im trying to call Three.register(onRegisterListener); but the server always responds with: 

    Http response:
    400 : Bad Request
    Service response:
    20303 : authorization token is invalid or contains invalid field(s) null

I have got the virgil token fine and made an ethree instance, but register always fails for me. Please help.

**Comment by BavovnaIsTaken** [comment]
Hi, @amiga !
Please, double check whether the credentials you're using are correct, or better try to create a fresh new test Application. 
Often this issue occurs when credentials are wrong. As well you can check your token with jwt.io if it's not expired by the time of your request (notice the time zone that you generate token in and time zone that checks it).
Does that help?

**Comment by amigax** [comment]
> Hi, @amiga !
> Please, double check whether the credentials you're using are correct, or better try to create a fresh new test Application.
> Often this issue occurs when credentials are wrong. As well you can check your token with jwt.io if it's not expired by the time of your request (notice the time zone that you generate token in and time zone that checks it).
> Does that help?

Yes, as we discovered in your slack channel I was actually sending the wrong identity, so it appears it was not a problem with this api. Thanks.

**Comment by leomorpho** [comment]
For anyone else facing this issue, I created a new app in the Virgile E3 Dashboard, and it worked after that...not sure why the first app I created didn't...Thanks for the pointer @BuddahLD
